Installer:
- Architecture: x86
  InstallerUrl: https://github.com/jesseduffield/lazygit/releases/download/v0.46.0/lazygit_0.46.0_Windows_32-bit.zip
- Architecture: x64
  InstallerUrl: https://github.com/jesseduffield/lazygit/releases/download/v0.46.0/lazygit_0.46.0_Windows_x86_64.zip
- Architecture: arm64
  InstallerUrl: https://github.com/jesseduffield/lazygit/releases/download/v0.46.0/lazygit_0.46.0_Windows_arm64.zip
- Architecture: neutral
  InstallerUrl: https://github.com/jesseduffield/lazygit/releases/download/v0.46.0/lazygit_0.46.0_Windows_armv6.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    It's time for another Lazygit release! Thanks to all who contributed to this release.
    What's Changed
    Enhancements üî•
    - Preserve pending commit message when closing/re-opening by @AzraelSec in https://github.com/jesseduffield/lazygit/pull/4191
    - Swap position of checkout-commit and checkout-branch menu items by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4238
      - In a previous release we had made it so that when you press space on a commit, the first option in the menu was to check out the corresponding branch, rather than the commit itself. We've made it so that now the first option is to check out the commit itself, for the sake of everybody's muscle memory.
    - Allow user to filter the files view to only show untracked files by @jesseduffield in https://github.com/jesseduffield/lazygit/pull/4226
    - Expose {{.SelectedCommitRange}} to custom commands by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4204
    - Show background fetch status in bottom line by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4215
    - Support copying tags to clipboard by @brunofjesus in https://github.com/jesseduffield/lazygit/pull/4218
    - Add option to delete local and remote tag by @AnvarU in https://github.com/jesseduffield/lazygit/pull/4217
    - Show confirmation menu when trying to amend changes while there are conflicts by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4222
    - Improve error reporting on config migration by @kas2020-commits in https://github.com/jesseduffield/lazygit/pull/4210
    - Show files filter status by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4230
    - Improve contrast of highlighted search results by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4242
    Fixes üîß
    - Don't try killing processes if we already know the command finished by @brandondong in https://github.com/jesseduffield/lazygit/pull/4231
      - We believe this was causing all sorts of problems for windows users.
    - Add '--' to 'git rev-list' to disambiguate branch name from path by @efussi in https://github.com/jesseduffield/lazygit/pull/4185
    - Fix adding blank line at end of commit message by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4182
    - Fix checking out a different branch while pushing a branch for the first time by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4214
    - Fix tag being truncated when copying to clipboard by @brunofjesus in https://github.com/jesseduffield/lazygit/pull/4232
    - Disable staging and unstaging lines or hunks when the diff context size is 0 by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4235
    - Fix incorrect stash diff after rename by @brandondong in https://github.com/jesseduffield/lazygit/pull/4213
    - Fix possible crash when deleting a branch while filtering is active by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4195
    - Fix pasting multi-line text into commit message panel by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4234
    - fix: properly detect icon for BAZEL and WORKSPACE files by @PeterCardenas in https://github.com/jesseduffield/lazygit/pull/4252
    - Fix json schema for context of CustomCommand by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4255
    Maintenance ‚öôÔ∏è
    - Bump go-deadlock version to fix crash with go 1.23 in debug mode by @ChrisMcD1 in https://github.com/jesseduffield/lazygit/pull/4248
    - Fix auto-release workflow by @jesseduffield in https://github.com/jesseduffield/lazygit/pull/4265
    I18n üåé
    - Update translations; includes a new Portuguese translation by @stefanhaller in https://github.com/jesseduffield/lazygit/pull/4250
    New Contributors
    - @efussi made their first contribution in https://github.com/jesseduffield/lazygit/pull/4185
    - @brunofjesus made their first contribution in https://github.com/jesseduffield/lazygit/pull/4218
    - @AnvarU made their first contribution in https://github.com/jesseduffield/lazygit/pull/4217
    - @kas2020-commits made their first contribution in https://github.com/jesseduffield/lazygit/pull/4210
    - @ChrisMcD1 made their first contribution in https://github.com/jesseduffield/lazygit/pull/4248
    - @PeterCardenas made their first contribution in https://github.com/jesseduffield/lazygit/pull/4252
    Full Changelog: https://github.com/jesseduffield/lazygit/compare/v0.45.2...v0.46.0
- Key: ReleaseNotesUrl
  Value: https://github.com/jesseduffield/lazygit/releases/tag/v0.46.0
Version: 0.46.0
ReleaseTime: 2025-02-15T04:56:31.0000000Z
